name: On Commit

on:
  push:
    branches:
      - main

jobs:
  on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: List changed files
        run: |
          # Get the list of committed files in the most recent push
          COMMITTED_FILES=$(git diff --name-only ${{ github.sha }}^)
          echo "Committed files: $COMMITTED_FILES"
        id: list_files

      - name: Get file content
        id: get_file_content
        run: |
          ALL_CONTENT=""
          for file in $COMMITTED_FILES; do
            echo "Fetching content for $file"
            FILE_CONTENT=$(git show ${{ github.sha }}:$file)
            ALL_CONTENT="$ALL_CONTENT\n$file:\n$FILE_CONTENT\n"
          done
          echo "$ALL_CONTENT"
        shell: bash
