name: On Commit

on:
  push:
    branches:
      - main

jobs:
  on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        run: |
          COMMITTED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Committed files: $COMMITTED_FILES"
        id: list_files

      - name: Get file content
        id: get_file_content
        run: |
          git show ${{ github.sha }}:$COMMITTED_FILES
        shell: bash

      - name: Display file content
        run: |
          echo "File content:"
          echo "${{ steps.get_file_content.outputs.stdout }}"
