name: On Commit

on:
  push:
    branches:
      - main

jobs:
  on-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: List changed files
        run: |
          # Get the list of committed files in the most recent push
          COMMITTED_FILES=$(git diff --name-only ${{ github.sha }}^) >> $GITHUB_OUTPUT
          echo "Committed files: $COMMITTED_FILES"
        shell: bash
        id: list_commit_files

      - name: Get file content
        run: |
          set -x  # Enable debugging to show the echo statements
          echo ${{ steps.list_commit_files.outputs.COMMITTED_FILES }}
          for file in ${{ steps.list_commit_files.outputs.COMMITTED_FILES }}; do
            echo "Fetching content for $file"
            FILE_CONTENT=$(git show ${{ github.sha }}:$file)
            # Append the content of each file to the array
            COMMITTED_FILE_CONTENTS+=("$file:$FILE_CONTENT")
          done
        shell: bash

      - name: Display file contents
        run: |
          set -x  # Enable debugging to show the echo statements
          # Loop through the array of committed file contents and display them
          for file_content in "${COMMITTED_FILE_CONTENTS[@]}"; do
            echo "File Content: $file_content"
          done
        shell: bash
